routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\ExperienceController;
use App\Http\Controllers\frontController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\ProjectController;
use PhpParser\Node\Expr\FuncCall;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});


Route::get('/dashboard', function () {
    return view('admin.index');
})->name('dashboard');


Route::get('/', [frontController::class, 'index']);
Route::get('/mail', [MailController::class, 'index']);

Route::resource('skills', SkillController::class);
Route::resource('experiences', ExperienceController::class);
Route::resource('projects', ProjectController::class);

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Observers\SkillObserver;
use Illuminate\Notifications\Notifiable;

class Skill extends Model
{
    use HasFactory, Notifiable;
    protected static function boot() {
        parent::boot();
        static::observe(SkillObserver::class);
    }
    protected $fillable = [
        'name',
        'photo',
        'status',
    ];
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Requests;
use App\Http\Requests\Skills\StoreSkill;
use App\Models\Skill;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class SkillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $skills = Skill::get();
        return view('admin.skills.index', compact('skills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create()
    {
        return view('admin.skills.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(StoreSkill $request)
    {
        $skills = new Skill;
        $skills->name = $request->name;
        $skills->status = $request->status;
        $skills->save();
        return redirect('/skills')->with(['success' => 'Skill has been created.']);
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show($id)
    {
        $skills = Skill::find($id);
        return view('admin.skills.show', compact('skills'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
    {
        $skills = Skill::find($id);
        return view('admin.skills.edit', compact('skills'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, $id)
    {
        $skills = Skill::find($id);
        $skills->name = $request->name;
        $skills->status = $request->status;
        $skills->save();
        return redirect('/skills');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
    {
        $skills = Skill::find($id)->delete();
        return redirect('/skills')->with(['success' => 'Skill has been deleted.']);
    }
}

resources/views/admin/skills/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Add Skill
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Create Skill</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('skills.index') }}">Skills</a>
                </li>
                <li class="active mt-3">
                    <strong>Add</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save</button>
        </div>
    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('skills.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Skill Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                    <div class="col-md-12">

                                        <div class="form-group @error('name') has-error @enderror">
                                            <label for="name">Name <span class="text-danger">*</span></label>
                                            <input type="text" placeholder="Enter name" class="form-control" name="name" id="name" value="{{ old('name') }}">
                                            @error('name')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group @error('status') has-error @enderror">
                                            <label for="status">Status</label>
                                            <select class="form-control" name="status" id="status">
                                                <option>Select</option>
                                                <option @if(old('status') == 'active') selected @endif value="active">Active</option>
                                                <option  @if(old('status') == 'inactive') selected @endif value="inactive">Inactive</option>
                                                @error('status')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                            </select>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Uploaded Photo</h5>
                        </div>
                        <div class="ibox-content">
                            <input type="file" class="dropify" name="file" />
                            @error('file')
                            <span class="text-danger"> {{ $message }} </span>
                            @enderror
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <script>
        $('.dropify').dropify();

        $(document).on('click', '#save-data', function(){
            $('form').submit();
        });


    </script>

@endsection

resources/views/admin/skills/edit.blade.php
@extends('layouts.dashboard')

@section('title')
     Edit Skill
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Edit Skill Form</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('skills.index') }}">Skills</a>
                </li>
                <li class="active mt-3">
                    <strong>Edit Skill</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save</button>
        </div>
    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('skills.update',$skills->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Skill Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                    <div class="col-md-12">

                                        <div class="form-group @error('name') has-error @enderror">
                                            <label for="name">Name <span class="text-danger">*</span></label>
                                            <input type="text" placeholder="Enter name" class="form-control" name="name" id="name" value="{{ $skills->name }}">
                                            @error('name')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group @error('status') has-error @enderror">
                                            <label for="status">Status</label>
                                            <select class="form-control" name="status" id="status">
                                                <option>Select</option>
                                                <option value="active" {{ $skills->status == 'active' ? 'selected' : '' }}>Active</option>
                                                <option value="inactive" {{ $skills->status == 'inactive' ? 'selected' : '' }}>Inactive</option>
                                            </select>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Uploaded Photo</h5>
                        </div>
                        <div class="ibox-content">
                            <input type="file" class="dropify" name="file" data-default-file="{{ asset('assets/uploads/skill-uploads/skills/'. $skills->photo ) }}" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <script>
        $('.dropify').dropify();

        $(document).on('click', '#save-data', function(){
            $('form').submit();
        });


    </script>

@endsection

resources/views/admin/skills/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Skills
@endsection

@section('css')
    <link href="{{ asset('assets/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endsection

@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
        <h2>Skills</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">Home</a>
            </li>
            <li class="active">
                <strong>Skills</strong>
            </li>
        </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('skills.create') }}" class="btn btn-primary mt-3">
                <span class="fa fa-plus"></span>
                Add</a>
        </div>
    </div>
@endsection

@section('content')

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Skills List
                    </h5>
                </div>
                <div class="ibox-content">

                <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover skills-table" >
                    <thead>
                        <tr>
                            <th>Photo</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($skills as $skill)
                            <tr>
                                <td>
                                    <img src="{{ asset('assets/uploads/skill-uploads/skills/'. $skill->photo ) }}" alt="" height="80" width="80">

                                </td>
                                <td>{{ $skill->name }}</td>
                                <td>
                                    @if ($skill->status == 'active')
                                        <span class="label label-primary">Active</span>
                                    @else
                                        <span class="label label-danger">In-Active</span>
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{route('skills.show',$skill->id) }}" class="btn-white btn btn-xs" >View</a>

                                        <a href="{{route('skills.edit',$skill->id) }}" class="btn-white btn btn-xs">edit</a>

                                        <form action="{{ route('skills.destroy',$skill->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn-white btn btn-xs">Delete</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                </div>
                </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('script')
    {{-- Datatable --}}
    <script src=" {{ asset('assets/js/plugins/dataTables/datatables.min.js') }}"></script>

    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function(){
            $('.skills-table').DataTable();

            @if(session('success'))
                toastr.success('{{ session("success") }}', 'Success');
            @endif


            $('.delete-skill').click(function () {

                let experienceId = $(this).data('skill-id');

                // Generate Token method 1
                // let token = $("meta[name='csrf-token']").attr("content");

                // Generate Token method 2
                let token = '{{ csrf_token() }}';

                let url = '{{ route("skills.destroy", ":id") }}';
                url = url.replace(':id', skillId);

                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this data!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                }, function () {

                    $.ajax(
                    {
                        url: url,
                        type: 'POST',
                        data: {
                            "_token": token,
                            "_method": 'DELETE',

                        },
                        success: function (){
                            swal("Deleted!", "skill has been deleted.", "success");
                            setTimeout(() => {
                                location.reload();
                            }, 3000);
                        }
                    });

                });
            });

        });
    </script>
@endsection

resources/views/admin/skills/show.blade.php
@extends('layouts.dashboard')

@section('title')
    Show Skill
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Show Skill</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Home</a>
                </li>
                <li>
                    <a href="{{ route('skills.index') }}">Skills</a>
                </li>
                <li class="active mt-3">
                    <strong>Show Skill</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('skills.index') }}" class="btn btn-warning mt-3 font-bold" id="save-data"> <span class="fa fa-arrow-left"></span> Cancel</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('skills.show', $skills->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-lg-9">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Skill Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">
                                    <div class="col-md-12">

                                        <div class="form-group @error('name') has-error @enderror">
                                            <label for="name">Name <span class="text-danger">*</span></label>
                                            <input type="text" placeholder="Enter name" class="form-control" name="name" id="name" value="{{ $skills->name }}">
                                            @error('name')
                                                <span class="text-danger"> {{ $message }} </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group @error('status') has-error @enderror">
                                            <label for="status">Status</label>
                                            <select class="form-control" name="status" id="status">
                                                <option>Select</option>
                                                <option value="active" {{ $skills->status == 'active' ? 'selected' : '' }}>Active</option>
                                                <option value="inactive" {{ $skills->status == 'inactive' ? 'selected' : '' }}>Inactive</option>
                                            </select>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Uploaded Photo</h5>
                        </div>
                        <div class="ibox-content">
                            <input type="file" class="dropify" name="file" data-default-file="{{ asset('assets/uploads/skill-uploads/skills/'. $skills->photo ) }}" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <script>
        $('.dropify').dropify();

        $(document).on('click', '#save-data', function(){
            $('form').submit();
        });


    </script>

@endsection