routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\ExperienceController;
use App\Http\Controllers\frontController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\ProjectController;
use PhpParser\Node\Expr\FuncCall;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});


Route::get('/dashboard', function () {
    return view('admin.index');
})->name('dashboard');


Route::get('/', [frontController::class, 'index']);
Route::get('/mail', [MailController::class, 'index']);

Route::resource('skills', SkillController::class);
Route::resource('experiences', ExperienceController::class);
Route::resource('projects', ProjectController::class);

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>@yield('title')</title>

        {{-- Bootstrap --}}
        <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">

        {{-- Font Awesome --}}
        <link href="{{ asset('assets/font-awesome/css/font-awesome.css') }}" rel="stylesheet">

        {{-- Animate Css --}}
        <link href="{{ asset('assets/css/animate.css') }}" rel="stylesheet">

        {{-- Style --}}
        <link href="{{ asset('assets/css/dashboard_style.css') }}" rel="stylesheet">

        {{-- Custom Css --}}
        <link href="{{ asset('assets/css/dashboard_custom.css') }}" rel="stylesheet">

        {{-- Datepicker --}}
        <link href="{{ asset('assets/css/plugins/datapicker/datepicker3.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/css/plugins/toastr/toastr.min.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/css/plugins/seetalert/sweetalert.css') }}" rel="stylesheet">

        @yield('css')

    </head>

    <body class="pace-done">
        <div class="pace  pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(100%, 0px, 0px);">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
        </div>

        <div id="wrapper">

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                    <div class="dropdown profile-element">
                        <span>
                        <img alt="image" class="img-circle" src="{{ asset('assets/images/my.jpg') }}" height="50" width="50">
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">
                           Rohinee Tandekar
                        </strong>
                        </span> <span class="text-muted text-xs block">Full Stack Developer</span> </span> </a>

                    </div>
                    <div class="logo-element">
                        IN+
                    </div>
                    </li>

                    <li>
                        <a href="{{ route('dashboard') }}"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
                    </li>

                    <li>
                        <a href="index-2.html"><i class="fa fa-user"></i> <span class="nav-label">Portfolio</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="{{ route('skills.index') }}">Skills</a></li>
                            <li><a href="{{ route('projects.index') }}">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-gears"></i> <span class="nav-label">Settings</span></a>
                    </li>
                </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg" style="min-height: 240px;">

            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" action="http://webapplayers.com/inspinia_admin-v2.5/search_results.html">
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                        </a>
                        <ul class="dropdown-menu dropdown-messages">
                            <li>
                                <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="img/a7.jpg">
                                </a>
                                <div class="media-body">
                                    <small class="pull-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="img/a4.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="img/profile.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                <a href="mailbox.html">
                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="mailbox.html">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="profile.html">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="grid_options.html">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                <a href="notifications.html">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                                </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                        <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                    </ul>
                </nav>
            </div>

            @yield('breadcrum')

            <div class="wrapper wrapper-content animated fadeInRight">
                @yield('content')
            </div>

            <div class="footer">
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Copyright</strong> Example Company © 2014-2015
                </div>
            </div>

        </div>
        </div>

        <!-- Mainly scripts -->
        <script src="{{ asset('assets/js/jquery-2.1.1.js') }}"></script>
        <script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('assets/js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
        <script src="{{ asset('assets/js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>

        <!-- Custom and plugin javascript -->
        <script src="{{ asset('assets/js/inspinia.js') }}"></script>
        <script src="{{ asset('assets/js/plugins/pace/pace.min.js') }}"></script>

        <!-- Toastr -->
        <script src="{{ asset('assets/js/plugins/toastr/toastr.min.js') }}"></script>
        <script src="{{ asset('assets/js/plugins/toastr/sweetalert.min.js') }}"></script>

        <!-- Datepicker -->
        <script src="{{ asset('assets/js/plugins/datapicker/bootstrap-datepicker.js') }}"></script>

        @yield('script')


    </body>

 </html>